### ISSUE TITLE
Problem with getting logs from Xray core When we save logs

### ISSUE THREAD

**Issue by houshmand-2005** [Gozargah/Marzban#672]
Hi, The problem is that when we save logs, logs are no longer displayed in the panel and API
<hr>

After change config(xray_config.json) like this
```json
"log": {
    "loglevel": "info",
    "access": "access.log",
    "error": "error.log"
  },
```
This is what Api and Panel shows:
```
Xray 1.8.4 (Xray, Penetrates Everything.) Custom (go1.21.0 linux/amd64)

A unified platform for anti-censorship.
2023/11/22 16:59:16 [Info] infra/conf/serial: Reading config: stdin:

```
And this is the contents of  `access.log` file (this is right and ok):
```
2023/11/22 17:01:32 192.168.1.33:11421 accepted tcp192.168.1.36:443 [VLESS_INBOUND -> proxy] email: 1.Test
2023/11/22 17:01:36 192.168.1.33:11424 accepted tcp192.168.1.36:443 [VLESS_INBOUND -> proxy] email: 1.Test
2023/11/22 17:01:37 192.168.1.33:11430 accepted tcp192.168.1.36:443 [VLESS_INBOUND -> proxy] email: 1.Test
```

As I can understand when with Xray we save the logs Xray doesn't show them on stdout, so marzban can't catch them.
This is [Marzban code](https://github.com/Gozargah/Marzban/blob/7dfbe1dc7e4864c27360e47f4d7567db4cdc65e4/app/xray/core.py#L68C1-L71C1) to get logs:

```python
    ...
    def capture_only():
        while self.process:
            output = self.process.stdout.readline()
            if output:
                output = output.strip()
                ...
```

so marzban just read the stdout and when Xray is saving log file, it doesn't send logs into stdout.

I found this out when someone reported it in my script   https://github.com/houshmand-2005/V2IpLimit/issues/32

And if we remove the save location to just show the logs like this:
```json
"log": {
    "loglevel": "info"
  },
```
Again the logs are sent without any problem.

<hr>

Do you think something can be done for this?

**Comment by omid-sadeghi** [comment]
با سلام
این رفتار پنل مرزبان که وقتی لاگ رو ذخیره می‌کنیم، دیگه لاگ نشون نمیده باعث میشه که اگر لاگ رو در فایل ذخیره کنیم اسکریپت V2IpLimit از کار بیفته چون این اسکریپت از لاگ های پنل مرزبان برای شمردن تعداد آیپی های هر کاربر استفاده میکنه.

**Comment by M03ED** [comment]
this problem should be solved in [Gozargah-Node](https://github.com/M03ED/gozargah-node/tree/dev), you can test it
this is going to be replaced with current node in Version 1

**Comment by M03ED** [comment]
fixed on next branch

**Comment by mikoff** [comment]
The problem is still there, whenever you add a custom log/access file location, their contents stops showing up in web-ui.
E.g.:
```
  "log": {
    "error": "/var/lib/marzban-node/error.log",
    "access": "/var/lib/marzban-node/access.log",
    "loglevel": "error"
  },
```
then nothing is visibgle in web-ui, all the paths ofc exist and logfiles are there.
